### PR TITLE
[#156087843] remove generated files

### PR DESCRIPTION
**Pull request by gunzip**
remove generated files from openapi specs, under lib/api/** to improve code reviews.
moreover this plays better with codeclimate / danger.js

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * ⚙️ [#156087843](https://www.pivotaltracker.com/story/show/156087843): Rimuovere i file generati dal repository Git

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cloudify** [comment]
Is the build/release process unaffected?

**Comment by gunzip** [comment]
I've added generate:models in the yarn build task which is configured in circle-ci before yarn test

**Comment by cloudify** [comment]
yes we also have a release process that is executed locally, I don't remember whether that process will run the build or not, pls check

**Comment by gunzip** [comment]
it does

```
    "release:git:checkout:funcpack",
    // build and run funcpack
    "yarn:build",
    "yarn:funcpack",
    // commits and pushes funcpack branch
    "release:git:commit:funcpack",
    "release:git:push:funcpack",
    "release:git:push:funcpack:latest",

```

**Pull request merged**
