### PR TITLE
[#153815768] documentdb field _ts is s anumber

### PR DESCRIPTION
**Pull request by gunzip**
removed overridde since they've patched the typings

ref. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22291

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🐞 [#153815768](https://www.pivotaltracker.com/story/show/153815768): Rimuovere l'ovverride del tipo _ts dai types di documentdb

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cloudify** [comment]
can you pls link in the PR description to the relevant commit/PR? (just for reference)

**Comment by cloudify** [comment]
no need to update the client library?

**Comment by gunzip** [comment]
linked. the library was already updated :)

**Pull request merged**
